# Generated by Django 4.2.2 on 2023-06-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocontent',
            name='content_path',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
