# Generated by Django 4.2.2 on 2023-07-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_photocontent_content_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocontent',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Wait approved'), (1, 'Approved'), (-1, 'Rejected'), (-2, 'On edit'), (-100, 'Dont show')], default=0),
        ),
        migrations.CreateModel(
            name='PhotoChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_photo', to='Services.photocontent', unique=True)),
                ('id_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_photo', to='Services.photocontent')),
            ],
        ),
    ]
