# Generated by Django 4.2.2 on 2023-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_photocontent_status_photochange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocontent',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
