# Generated by Django 4.2.2 on 2023-07-10 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_photocontent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photochange',
            name='id_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_photo', to='Services.photocontent', unique=True),
        ),
        migrations.AlterField(
            model_name='photochange',
            name='id_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_photo', to='Services.photocontent'),
        ),
    ]
